"""gameRecord table

Revision ID: b954b43b0e53
Revises: 8826d0acf733
Create Date: 2022-05-16 23:20:12.024599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b954b43b0e53'
down_revision = '8826d0acf733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Integer(), nullable=True),
    sa.Column('chance_remain', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_record_chance_remain'), 'game_record', ['chance_remain'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_record_chance_remain'), table_name='game_record')
    op.drop_table('game_record')
    # ### end Alembic commands ###
